### ISSUE TITLE
Breakout fxgl version cannot be resolved

### ISSUE THREAD

**Issue by wlnirvana** [AlmasB/FXGLGames#12]
Breakout uses dev-SNAPSHOT:

https://github.com/AlmasB/FXGLGames/blob/750b42cc733fff83eb6b582646c1d8794ba7e79f/Breakout/pom.xml#L19

but there does not seem to be that version in maven central

**Comment by AlmasB** [comment]
The dev-SNAPSHOT is loaded from a snapshot repository, defined in the same pom.xml. Perhaps your IDE isn't able to resolve the repository?

**Comment by wlnirvana** [comment]
Ah, I see. I happen to have a wildcard mirror in my maven setting, which is meant to be targeting central and jcenter, but unfortunately matches all repos. I fixed that and now all is well. Thanks for the explanation.
