### ISSUE TITLE
"Code samples" link on this page is broken

### ISSUE THREAD

**Issue by dukemagus** [AlmasB/FXGLGames#27]
Steps to reproduce: 

click on the links for "code samples", 

expected behavior: link to code samples

Actual behavior: error 404

suggestion: change the link from

`https://github.com/AlmasB/FXGL/tree/release/samples` 

to 

`https://github.com/AlmasB/FXGL/tree/release/fxgl-samples`

**Comment by AlmasB** [comment]
Thanks, fixed.
